name: thesis-nlp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pandas=2.1.4
  - numpy=1.23.3
  - scikit-learn=1.3.2
  - matplotlib=3.8.4
  - seaborn=0.13.2
  - nltk=3.8.1
  - spacy=3.5.3
  - gensim=4.3.2
  - umap-learn=0.5.5
  - pip:
      - torch==2.0.1
      - transformers==4.40.1
      - sentence-transformers==2.6.1
      - datasets==2.19.1
      - bertopic==0.16.0
      - hdbscan==0.8.40
      - openai==1.30.1
      - tqdm==4.66.2
      - pytest==8.2.1
      - black==24.4.2
      - isort==5.13.2
